config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index]
  resources :categories, except: [:show] do
    resources :deals, except: [:show]
  end
  devise_for :users
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end


  authenticated :user do
    root "categories#index", as: :authenticated_root
  end

  root "users#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    return unless user.present?

    can :read, :all
    can(:manage, Category, user:)
    can(:manage, Deal, user:)
    return unless user.admin?

    can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_one_attached :icon
  has_and_belongs_to_many :deals
  belongs_to :author, class_name: 'User'
  validates :name, presence: true, length: { minimum: 3 }
  validates :icon, presence: true
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :categories
  validates :name, presence: true, length: { minimum: 3 }
  validates :amount, numericality: { greater_than: 0 }
  validates :categories, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :purchases, dependent: :destroy
  has_many :groups, dependent: :destroy
  validates :name, presence: true, length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.where(author_id: current_user.id)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.author = current_user
    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_group
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: %i[show edit update destroy]
  before_action :set_category, except: %i[destroy create update]

  def index
    @categories = Category.where(author_id: current_user.id)
    @deals = @category.deals
    @total_amount = 0
    @deals.each do |deal|
      @total_amount += deal.amount
    end
  end

  def new
    @categories = Category.where(author_id: current_user.id)
    @deal = Deal.new
  end

  def create
    @deal = Deal.new(deal_params)
    @categories = Category.where(id: categories_params['categories'])
    @deal.categories << @categories
    @deal.author = current_user
    if @deal.save
      redirect_to category_deals_path, notice: 'Purchase was successfully created.'
    else
      redirect_to new_category_deal_path, alert: 'Failed to create purchase.'
    end
  end

  private

  def set_deal
    @deal = Deal.find(params[:id])
    @category = Category.find(params[:category_id])
  end

  def set_category
    @category = Category.find(params[:category_id])
  end

  def deal_params
    params.require(:deal).permit(:name, :amount)
  end

  def categories_params
    params.require(:deal).permit(categories: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class="flex flex-col h-full">
  <div class="flex flex-row w-[vw] bg-[#3778c2] p-3 text-white items-center justify-center">
    <p class="flex flex-row place-self-center">CATEGORIES</p>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class:"fixed right-3 flex flex-row place-self-center" %>
  </div>

  <div>
    <% @categories.each do |category| %>
      <%= link_to category_deals_path(category) do %>
  <div class="border-solid border-2 p-2 m-1 flex flex-row" id="<%= dom_id category %>" class="">
  <%= link_to category_deals_path(category), class: "flex flex-row justify-between w-full" do %>
    <%= image_tag(category.icon, size: "80x80", alt: "Group") %>

    <div class="flex flex-col justify-between">
      <p>
        Category:
        <strong><%= category.name %></strong>
      </p>

      <p>
        Total Transactions:
        <strong>$<%= category.deals.sum(:amount) %></strong>
      </p>
    </div>
  <% end %>
</div>
      <% end %>
    <% end %>
  </div>

  <div class="fixed bottom-0 p-3 bg-[#5fb523] text-white w-full">
    <button class="p-3 border-solid border-2 w-full" >
      <%= link_to "ADD CATEGORY", new_category_path %>
    </button>
  </div>
</div>

app/views/categories/new.html.erb
<div class="flex flex-col h-full w-full">
 <div class="flex flex-row w- bg-[#3778c2] p-3 text-white items-center justify-center">
 <div class="fixed left-3">
    <%= link_to categories_path, class: "" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
  </svg>
  </div>
    <% end %>
    <p class="flex flex">CATEGORIES</p>
  </div>

  <% if @category.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

    <ul>
      <% @category.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="flex flex-col justify-center justify-items-center h-full p-5">
<%= form_with(model: @category, class: "flex flex-col justify-center justify-items-center" ) do |form| %>

  <%= form.text_field :name, autofocus: true, autocomplete: "name",
    class: "w-full p-2 mb-1 border-solid border-2", placeholder: "Name"
  %>

  <div class="w-100 p-2 mb-1 bg-white rounded">
    <%= form.label :icon, style: "w-full p-2 mb-1 border-solid border-2" %>
    <%= form.file_field :icon %>
  </div>
</div>
  <div class="fixed bottom-0 p-3 bg-[#5fb523] text-white w-full">
    <%= form.submit "Add", class: "p-3 border-solid border-2 w-full" %>
  </div>
<% end %>

</div>

app/views/deals/index.html.erb
<div class="">
   <div class="flex flex-row w- bg-[#3778c2] p-3 text-white items-center justify-center">
    <div class="fixed left-3">
    <%= link_to categories_path, class: "" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
  </svg>
  </div>
    <% end %>
    <p class="flex flex">Transactions</p>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class:"fixed right-3 flex flex-row place-self-center" %>
  </div>

  <div class="">
    <p class="border-solid border-b-2 p-2 flex flex-row justify-between">
      Total Amount:
      <strong>$<%=@total_amount %></strong>
    </p>
  </div>

  <div>
    <% @deals.each do |deal| %>
      <div id="<%= dom_id deal %>" class="">
      <div class="p-3 flex flex-col gap-4 border-solid border-2">
    <p>
      <strong>Name:</strong>
      <%= deal.name %>
    </p>

    <p>
      <strong>Amount:</strong>
      $<%=  + deal.amount %>
    </p>
  </div>
</div>
    <% end %>
  </div>

  <div class="fixed bottom-0 p-3 bg-[#5fb523] text-white w-full">
    <button class="p-3 border-solid border-2 w-full">
      <%= link_to "Add Transaction", new_category_deal_path %>
    </button>
  </div>
</div>

app/views/deals/new.html.erb
<div class="flex flex-col h-full w-full">
  <div class="flex flex-row w- bg-[#3778c2] p-3 text-white items-center justify-center">
   <div class="fixed left-3">
    <%= link_to category_deals_path, class: "btn" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
  </svg>
  </div>
    <% end %>
    <p class="navbar-brand m-0 text-light position-absolute top-50 start-50 translate-middle">PURCHASES</p>
  </div>

<% if @deal.errors.any? %>
  <div style="color: red">
    <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this category from being saved:</h2>

    <ul>
      <% @deal.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="flex flex-col justify-center justify-items-center h-full p-5">
<%= form_with(model: [@category, @deal], class: "flex flex-col justify-center justify-items-center") do |form| %>
  <%= form.text_field :name, autofocus: true, autocomplete: "name",
    class: "w-full p-2 mb-1 border-solid border-2", placeholder: "Name"
  %>

  <%= form.number_field :amount, autofocus: true, autocomplete: "amount",
    class: "w-full p-2 mb-1 border-solid border-2", placeholder: "Amount $"
  %>

  <div class="">
    <p> Categories: </p>
    <% @categories.each do |category| %>
      <% @is_checked = category.id == params[:category_id].to_i %>
      <div class="p-2 d-flex align-items-center">
        <%= form.label category.name, class: "w-25" %>
        <%= form.check_box :categories,
          { multiple: true, checked: @is_checked }, category.id, nil
        %>
      </div>
    <% end %>
  </div>

</div>
  <div class="fixed bottom-0 p-3 bg-[#5fb523] text-white w-full">
    <%= form.submit "Add", class: "p-3 border-solid border-2 w-full" %>
  </div>
<% end %>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body class="h-[100vh] w-[100vw]">
    <% if notice %>
      <p class="alert alert-success m-0"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger m-0"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div class="flex flex-col justify-center h-full gap-5">

  <div class="flex flex-col jutify-center gap-5">
  <img class="self-center" src="https://i.ibb.co/936C81d/Birre.png"  width="170" alt="Birre" border="0" />
    <button class="bg-[#3778c2] w-[100px] self-center rounded-lg p-3 text-white">
      <%= link_to 'LOG IN', new_user_session_path %>
    </button>

    <button class="bg-[#3778c2] w-[100px] self-center rounded-lg p-3 text-white">
      <%= link_to 'SIGN UP', new_user_registration_path %>
    </button>
  </div>
</div>